Move vlucas/phpdotenv from suggest to required dependency
In `helpers.php` in Laravel 5.8, `env` function needs `DotenvFactory` class. If `vlucas/phpdotenv` is not a required dependency, it will throw an error:

```
Error: Class 'Dotenv\Environment\DotenvFactory' not found
```

Moving `vlucas/phpdotenv` from suggest to required dependency can solve this problem.