[5.1] Encryption: Test the IV length in invalidPayload method
Lately, I have upgraded my website from L 4.2.11 to the latest one. The Encryption cipher used before was MCRYPT_RIJNDAEL_128 which uses an IV with a length of 32. Since the payload in the cookies in users was encrypted using the old cipher, the EncryptCookies middleware threw an exception with this trace:

production.ERROR: exception 'ErrorException' with message 'openssl_decrypt(): IV passed is 32 bytes long which is longer than the 16 expected by selected cipher, truncating' in /home/www/MY/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php:95

The obvious and simple trick would be to wrap the openssl_decrypt() in Encrypter.php:95 in a try catch block throwing a DecryptException exception, but this could be prevented since the beginning in the invalidPayload() method in the BaseEncrypter class by testing the length of the IV.

Since getIvSize() is used in the invalidPayload() method in the abstract invalidPayload() class, I declared it as an abstract method in it.
I would go ahead and define getIvSize() in the baseEnrypter class using openssl_cipher_iv_length() method, since the IV length might change in the future depending on the cipher declared in the config file.

At the end, this might be considered as supporting an old version of laravel which is no longer done.