Account for missing controller methods
Fixes test:

1) Illuminate\Tests\Routing\RouteRegistrarTest::testCanSetMiddlewareForSpecifiedMethodsOnRegisteredResource
ReflectionException: Method Illuminate\Tests\Routing\RouteRegistrarControllerStub::create() does not exist